### PR TITLE
updated code in ref/getting_started.md

### PR DESCRIPTION
**Pull request by haroldcarr**
these changes make the code work

except places with comments:

`# this gets : AttributeError: ...`
`# this gets : TypeError: ..`

### CODE REVIEW

**Review by pfeairheller — APPROVED** [review]

**Comment by pfeairheller** [comment]
You can remove the lines creating the nextKeyDig and change the messagize calls to name the second argument:

`
msg = eventing.messagize(srdr, sigers=sigers)
`

**Comment by haroldcarr** [comment]
I just did a commit that removes `nextKeyDig` and changes the calls to `messagize` appropriately.

However, I have now indicated one more error, pointed out by:

```
        # This is not defined (it should probably be `processEvent`).
        # Also, the real error is masked by this "catch".
        kevery.processOne(ims=msg)
```

**Comment by pfeairheller** [comment]
Yeah, that's some pretty old code there, lol.

If you add to the imports:

`import keri.core.parsing as parsing`

and the change the "processOne" line to:

`parsing.Parser().parseOne(ims=msg, kvy=kevery)`

It should work for you.

**Comment by haroldcarr** [comment]
OK.  I updated the "last" error.  All example in `getting_started.md` now work.
I find these examples as definitely the best place to see the code in action.
They should probably be made into tests/demos to ensure they are kept up-to-date.

**Comment by pfeairheller** [comment]
Everything in that file is in tests but sprinkled throughout `test_coring.py`, `test_eventing.py` and elsewhere.

I get your point about these concise examples being useful and needing to keep them up to date.

**Pull request merged**
